### ISSUE TITLE
How do I use?

### ISSUE THREAD

**Issue by ghost** [Pwnoz0r/TidalDownloader#1]
I'm a beginner, how do I install and use this?

**Comment by jonrainier** [comment]
If you do not want to compile it yourself, you can download the latest build from [here](https://github.com/Pwnoz0r/TidalDownloader/releases) and run it.
1. Launch the application after extracting it and enter your Tidal account information that has an active Tidal subscription.
2. Download the latest build of ffmpeg ([x86](https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-latest-win32-static.7z) or [x64](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z)) and extract it in the same directory as the TidalDownloader
3. After making all required changes to the settings form in the TidalDownloader, press save to save your changes and restart the application.
4. You should then see all the latest albums on Tidal appear on the main window of the application.
